"""Type stubs for the `poker_engine` extension module (see engine/README.md)."""

from typing import Optional, Sequence

import numpy as np
import numpy.typing as npt

FOLD: int
CHECK_CALL: int
RAISE: int
MAX_PLAYERS: int
HAND_CATEGORY_NAMES: list[str]
__version__: str

def evaluate5(cards: Sequence[int]) -> int: ...
def evaluate6(cards: Sequence[int]) -> int: ...
def evaluate7(cards: Sequence[int]) -> int: ...
def evaluate(cards: Sequence[int]) -> int: ...
def evaluate_batch(cards: npt.NDArray[np.uint8]) -> npt.NDArray[np.int32]: ...
def hand_category(rank: int) -> int: ...
def card_from_str(s: str) -> int: ...
def card_to_str(card: int) -> str: ...

class GameConfig:
    num_players: int
    stacks: list[int]
    small_blind: int
    big_blind: int
    ante: int
    def __init__(
        self,
        num_players: Optional[int] = None,
        stacks: Optional[Sequence[int]] = None,
        small_blind: int = 50,
        big_blind: int = 100,
        ante: int = 0,
    ) -> None: ...
    def validate(self) -> None: ...

class Action:
    kind: int
    amount: int
    def __init__(self, kind: int, amount: int = 0) -> None: ...
    @staticmethod
    def fold() -> Action: ...
    @staticmethod
    def check_call() -> Action: ...
    @staticmethod
    def raise_to(amount: int) -> Action: ...
    def __hash__(self) -> int: ...

class LegalActions:
    can_fold: bool
    can_check: bool
    call_amount: int
    min_raise_to: int
    max_raise_to: int
    can_raise: bool
    def is_legal(self, action: Action) -> bool: ...
    def clamp_raise_to(self, amount: int) -> int: ...

class GameState:
    @staticmethod
    def new_hand(config: GameConfig, button: int, deck: Sequence[int]) -> GameState: ...
    num_players: int
    button: int
    street: int
    board: list[int]
    stacks: list[int]
    street_bets: list[int]
    contributed: list[int]
    pot: int
    current_player: int
    is_terminal: bool
    folded: list[bool]
    all_in: list[bool]
    history: list[tuple[int, int, Action]]
    current_bet: int
    last_raise_size: int
    num_raises_this_street: int
    is_masked: bool
    config: GameConfig
    def hole_cards(self, player: int) -> list[int]: ...
    def legal_actions(self) -> LegalActions: ...
    def apply(self, action: Action) -> None: ...
    def child(self, action: Action) -> GameState: ...
    def clone(self) -> GameState: ...
    def payoffs(self) -> list[int]: ...
    def public_key(self) -> bytes: ...
    def infoset_key(self, player: int) -> bytes: ...
    def masked(self, viewer: int) -> GameState: ...
    def showdown_order(self) -> list[int]: ...
