"""Type stubs for the `poker_engine` extension module (see engine/README.md)."""

from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

FOLD: int
CHECK_CALL: int
RAISE: int
MAX_PLAYERS: int
HAND_CATEGORY_NAMES: list[str]
__version__: str

def evaluate5(cards: Sequence[int]) -> int: ...
def evaluate6(cards: Sequence[int]) -> int: ...
def evaluate7(cards: Sequence[int]) -> int: ...
def evaluate(cards: Sequence[int]) -> int: ...
def evaluate_batch(cards: npt.NDArray[np.uint8]) -> npt.NDArray[np.int32]: ...
def hand_category(rank: int) -> int: ...
def card_from_str(s: str) -> int: ...
def card_to_str(card: int) -> str: ...

class GameConfig:
    num_players: int
    stacks: list[int]
    small_blind: int
    big_blind: int
    ante: int
    def __init__(
        self,
        num_players: int | None = None,
        stacks: Sequence[int] | None = None,
        small_blind: int = 50,
        big_blind: int = 100,
        ante: int = 0,
    ) -> None: ...
    def validate(self) -> None: ...

class Action:
    kind: int
    amount: int
    def __init__(self, kind: int, amount: int = 0) -> None: ...
    @staticmethod
    def fold() -> Action: ...
    @staticmethod
    def check_call() -> Action: ...
    @staticmethod
    def raise_to(amount: int) -> Action: ...
    def __hash__(self) -> int: ...

class LegalActions:
    can_fold: bool
    can_check: bool
    call_amount: int
    min_raise_to: int
    max_raise_to: int
    can_raise: bool
    def is_legal(self, action: Action) -> bool: ...
    def clamp_raise_to(self, amount: int) -> int: ...

class GameState:
    @staticmethod
    def new_hand(config: GameConfig, button: int, deck: Sequence[int]) -> GameState: ...
    num_players: int
    button: int
    street: int
    board: list[int]
    stacks: list[int]
    street_bets: list[int]
    contributed: list[int]
    pot: int
    current_player: int
    is_terminal: bool
    folded: list[bool]
    all_in: list[bool]
    history: list[tuple[int, int, Action]]
    current_bet: int
    last_raise_size: int
    num_raises_this_street: int
    is_masked: bool
    config: GameConfig
    def hole_cards(self, player: int) -> list[int]: ...
    def legal_actions(self) -> LegalActions: ...
    def apply(self, action: Action) -> None: ...
    def child(self, action: Action) -> GameState: ...
    def clone(self) -> GameState: ...
    def payoffs(self) -> list[int]: ...
    def public_key(self) -> bytes: ...
    def infoset_key(self, player: int) -> bytes: ...
    def masked(self, viewer: int) -> GameState: ...
    def showdown_order(self) -> list[int]: ...

# ---------------------------------------------------------------------------
# Abstractions and the MCCFR solver (see pokerbot/blueprint/mccfr/README.md)
# ---------------------------------------------------------------------------

AbstractActionSpec = tuple  # ("fold",) | ("check_call",) | ("raise", float) | ("allin",)

def canonical_index(street: int, hole: Sequence[int], board: Sequence[int]) -> int: ...
def canonical_index_batch(street: int, cards: npt.NDArray[np.uint8]) -> npt.NDArray[np.uint32]: ...
def canonical_unindex(street: int, index: int) -> tuple[list[int], list[int]]: ...
def canonical_size(street: int) -> int: ...
def preflop_class(hole: Sequence[int]) -> int: ...
def pseudo_harmonic(a: float, b: float, x: float) -> float: ...
def hand_strength(
    hole: Sequence[int], board: Sequence[int], samples: int = 256, seed: int = 0
) -> float: ...
def make_infoset_key(street: int, bucket: int, sequence: Sequence[int]) -> int: ...
def decode_infoset_key(key: int) -> tuple[int, int, list[int]]: ...
def action_from(kind: int, amount: int) -> Action: ...

class ActionAbstraction:
    streets: list[list[AbstractActionSpec]]
    max_raises: int
    def __init__(self, streets: object | None = None, max_raises: int = 4) -> None: ...
    def legal(self, state: GameState) -> list[tuple[int, Action]]: ...
    def to_concrete(self, state: GameState, index: int) -> Action | None: ...
    def translate(
        self, abs_state: GameState, real_state: GameState, action: Action, u: float = 0.5
    ) -> int | None: ...
    def sequence(self, state: GameState) -> list[int]: ...
    def count_tree(self, config: GameConfig | dict, limit: int = ...) -> list[int] | None: ...
    @staticmethod
    def pot_fraction(state: GameState, raise_to: int) -> float: ...

class CardAbstraction:
    def __init__(
        self,
        buckets: Sequence[int] | None = None,
        hs_samples: int = 256,
        tables: Sequence[str | npt.NDArray[np.integer] | None] | None = None,
    ) -> None: ...
    def bucket(self, street: int, hole: Sequence[int], board: Sequence[int]) -> int: ...
    def buckets_batch(
        self, street: int, cards: npt.NDArray[np.uint8]
    ) -> npt.NDArray[np.uint32]: ...
    def num_buckets(self, street: int) -> int: ...

class Trainer:
    iterations: int
    config_json: str
    meta: str
    game_config: GameConfig
    def __init__(self, config: dict | None = None) -> None: ...
    def run(self, iterations: int, threads: int = 1) -> dict: ...
    def stats(self, detailed: bool = False) -> dict: ...
    def set_checkpoint(self, path: str | None, interval_seconds: float) -> None: ...
    def action_abstraction(self) -> ActionAbstraction: ...
    def bucket(self, street: int, hole: Sequence[int], board: Sequence[int]) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> Trainer: ...
    def export_strategy(self, path: str) -> int: ...
    def strategy(self, state: GameState, player: int, average: bool = True) -> list[float]: ...
    def infoset_key(self, state: GameState, player: int) -> int: ...
    def lookup(self, key: int) -> tuple[list[float], list[float]] | None: ...
    def entries(self) -> list[tuple[int, list[float], list[float]]]: ...

class BlueprintStrategy:
    config_json: str
    meta: str
    game_config: GameConfig
    def __init__(self, path: str) -> None: ...
    def __len__(self) -> int: ...
    def action_abstraction(self) -> ActionAbstraction: ...
    def bucket(self, street: int, hole: Sequence[int], board: Sequence[int]) -> int: ...
    def lookup(self, key: int) -> list[float] | None: ...
    def action_probs(
        self, abs_state: GameState, hole: Sequence[int], board: Sequence[int]
    ) -> tuple[list[int], list[Action], list[float], bool]: ...
